### ISSUE TITLE
Chose nickname instead of randomizing

### ISSUE THREAD

**Issue by troych** [TheAomx/xdccget#1]
Hi there,

Would it be possible to get an option to choose your nickname instead of just randomizing it? I guess one would also need the possibility to authenticate said nick. 

Reason being is that some networks "level" you up which in turn gets you some more features to use in the channel

**Comment by TheAomx** [comment]
Hi,
yes that would be possible to implement. I think that would be a useful feature for channels, that require you to login in ordner to send XDCC-Requests!

In order to login, i think the user would have to specify his nickname and his password. Maybe this can be done using another command line option. Do you have to issue a special CTCP-Request in order to login, after the irc-client has sucessfully connected to the irc-server?

**Comment by troych** [comment]
As far as I know most networks either work with nickserv or authserv or some other form of bot to authenticate, the ctcp request would be a new one for me.

with nickserv you'd be doing
/msg nickserv auth <password>

authserv is similar
/msg authserv auth <account> <password> 

Maybe the possibility to send a certain /msg on connect so stuff like this wouldn't be hardcoded?

**Comment by TheAomx** [comment]
Hi,
i just pushed a first implementation to resolve this issue:
https://github.com/TheAomx/xdccget/tree/implementation_of_issue_1

With this version you can now specify a nickname with the -n and an login-command with the -l flag.

So let's assume that you want to connect to channel #secret on server irc.server.net with nick TestNick and that the password would be hello. then you would call xdccget like:

'' xdccget -n TestNick -l "nickserv auth hello" "irc.server.net" "#secret" "TestBot xdcc send #1" ''

you can also use authserv at the login-command, if authserv is used. Please tell me, if you can login to the server now...! Maybe there are some problems and i send the xdcc send command to early or too late, so feedback would be great!

**Comment by troych** [comment]
Works, the waiting time is easily long enough too, took a while until the transfer started, so long in fact I almost thought something is broken. So I guess you could easily shorten that by quite a bit, even if you'd be joining 10+ channels with lots of users.

**Comment by TheAomx** [comment]
Thanks for your feedback and really nice that it already works!

Normally i send the xdcc-requests, when you join the channels. This does not work in this case, because you join so fast, that the nickserv or authserv system maybe has not validated the login-command and you are not logged in.

Do you know, if the auth-system like nickserv or authserv send some kind of feedback to the irc client when you are logged in? I think the best behaviour would be to recognize this event and then send the xdcc requests.

**Comment by troych** [comment]
I do get a message on my usual network, googled it and from what I can see this is the default one for most networks using nickserv.

```[Info] - Event "NOTICE", origin: "NickServ", params: 2 [nickname|Password accepted - you are now recognized.]```

**Comment by TheAomx** [comment]
Hi,
thanks for the info on that!

I will try to implement a method to recognize these events!

**Comment by TheAomx** [comment]
Hi,
i figured out, that when you receive this event you can still have no voice-rights on the channels and therefore the request can be denied. Therefore i have to wait for the MODE-Event, where the +v parameter is passed, which tells the client that you have acquired voice-rights on the channel.

I have implemented that behaviour in the current master-branch and i hope that this works now!

**Comment by troych** [comment]
Only had time for a quick test, worked very well, no waiting or anything out of the ordinary. I guess you can close this if you feel happy with the implementation. :) Thanks again for the time you took with my issues.

**Comment by TheAomx** [comment]
Hey,
nice to know that it works for you!
