### ISSUE TITLE
xdccget does not exit

### ISSUE THREAD

**Issue by troych** [TheAomx/xdccget#2]
Hi again,

Last one for today: I seem to be having trouble getting xdccget to gracefully exit, doesn't matter if I do ssend or send after the download completed and the checksum was verified it just sits there doing nothing. Only option is to kill it manually.

Is this intended behaviour or is something going wrong?

```
[###########################################################################################################################################] 100.00% 326.213 MByte/326.213 MByte|18.398 KByte/s|---
Download completed!
[Info] - Event "NOTICE", origin: "Botname", params: 2 [LyObbgcFcsIegAwKQipG|** SSL Transfer Completed (334042 kB, 34.128 sec, 9787.9 kB/sec, md5sum: 1557d6da6844abd516879f92b19d4ccd)]
[Info] - Verifying md5-checksum '1557d6da6844abd516879f92b19d4ccd'!
[Info] - Checksum-Verification succeeded! 

```

**Comment by TheAomx** [comment]
Hi,
this is at the moment intended behaviour. You stay connected to the server and the channels, because of the Checksum-Verification (because you often get after the download a NOTICE-Message with the checksum, so it would be bad to exit the programm, if the file is downloaded).

I could implement it that xdccget exits if the download is completed. But then the checksum verification would not work. If i exit xdccget after the checksum-notification then where would be a problem for channels, that dont provide checksums...!

**Comment by troych** [comment]
Thanks for the reply, would there be an easy way to tell when the download is finished, from bash for example? I'm trying to automate some of my downloads with a small bash script and just killing the xdccget process after a while doesn't sound like a very scientific approach. :D

**Comment by TheAomx** [comment]
Yes, i think i will change the default behaviour, so that xdccget exits with return code 0, if the file was downloaded sucessfully. Then the automatic checksum-verification does not work obviously, but i think all command-line tools like wget or curl behave that way.

I think i will add another option, so that xdccget does not exit after download. This option can be set using the config-file or directly with an command line argument. In that case the checksum-verification will work!

Then the users can decide which behaviour they would like to use!

**Comment by troych** [comment]
Sounds like a good plan! :+1:

**Comment by TheAomx** [comment]
Hi,
i have just pushed a commit regarding this issue. xdccget now exits after all downloads are finished. if you call xdccget with -c or --checksum-verify then it will wait for the checksum-notice-message and therefore has to be manually killed!

**Comment by troych** [comment]
Just did a quick test, works as advertised, thanks a lot. :)
